### ISSUE TITLE
Support for non-HDLC?

### ISSUE THREAD

**Issue by cenobitedk** [horfic/esphome-dlms#1]
Hi! Found your component and I like how clean the code is! 👌

I'm currently using [this component](https://github.com/psvanstrom/esphome-p1reader) but I'd rather use yours since it has better integration with esphome (the python files), and because it's nicer. 😄 

However there's a few things stopping me from actually using your component:
- **Decryption key is required**, this should be optional
- **Only supports HDLC**, which doesn't work with my meter (Landis+Gyr E360)

Making the decryption key optional is not a big deal (I believe), but I have no idea about the HDLC, would it be possible to add support for non-HDLC (I don't know the correct term)?

**Comment by horfic** [comment]
Hi,
First of all, thank you.

The project was never finished, still got issues with decryption validation. That said I was planning at one point to support more protocols.

The integration was done as I did not find a lot of e450 from Stromnetz Graz implementations. And it appears that they work again differently to the ones you find online.

To actually support the e360 In this code I would actually need to know your provider, what protocol it actually is using and possibly raw uart logs from your device to test with.

Did you try already this directly from esphome?
https://esphome.io/components/sensor/dsmr.html

Cheers

**Comment by cenobitedk** [comment]
Thanks for your reply!

> The integration was done as I did not find a lot of e450 from Stromnetz Graz implementations. And it appears that they work again differently to the ones you find online.

Ah ok, I see.

> Did you try already this directly from esphome?
> https://esphome.io/components/sensor/dsmr.html

Nope, did not. I'm in Denmark and my meter supports dlms and I read (can't find the source) that dsmr and dlms are different, one being binary, the other not. But it's definitely worth a shot :)

**Comment by cenobitedk** [comment]
So I tried the dsmr component and it works just fine. 👍 

My only problem with it is that it's more or less a subset of dlms and thus doesn't support all obis codes and some of them are badly labelled. 🤷‍♂️ but it'll do for now. I wish there's was a proper dlms component for esphome and the dsmr component was just a layer on that.

Thanks for your work. If you ever complete the component, consider making a PR to the esphome repo, so that others can benefit from a proper dlms component. 😄
